management:
  context-path: /admin
  security:
    enabled: false

server:
  port: 8899

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///home/dkaczynski/Devel/Spring/spring-io-lab10-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
