version: '3'
services:
  data:
    image: "mongo:3.0"
    ports:
      - "27017:27017"
    volumes:
      - ".data:/data/db"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "root"
#      MONGO_INITDB_ROOT_PASSWORD: "sprio"
#      MONGO_INITDB_DATABASE: "marketing"
